# LER Search Configuration

# Date Range
date_range:
  start:
    month: "Jan"     # 1월부터 검색
    day: "1"
    year: "2021"
  end:
    month: "Dec"     # 12월까지 검색
    day: "31"
    year: "2023"

# Reactor Type (체크박스 ID: ContentPlaceHolderMainPageContent_CheckBox{Type})
reactor_types:
  BWR: false    # Boiling Water Reactor
  PWR: true     # Pressurized Water Reactor
  HGTR: false   # High Gas Temperature Reactor

# Vendor Selection (체크박스 ID: ContentPlaceHolderMainPageContent_CheckBox{Vendor})
vendors:
  BabcockWilcox: false            # Babcock & Wilcox
  CombustionEngineering: false    # Combustion Engineering
  GeneralElectric: false          # General Electric
  Westinghouse: true              # Westinghouse
  Other: false                    # Other Vendors

# NRC Regions (체크박스 ID: ContentPlaceHolderMainPageContent_CheckBoxRegion{I/II/III/IV})
nrc_regions:
  I: true       # Region I
  II: true      # Region II
  III: true     # Region III
  IV: true      # Region IV

# Operating Modes (체크박스 ID: ContentPlaceHolderMainPageContent_CheckBox{Mode})
operating_modes:
  PowerOperation: true    # Power Operation
  HotShutdown: true      # Hot Shutdown
  Refueling: true        # Refueling
  Startup: true          # Startup
  ColdShutdown: true     # Cold Shutdown
  Other: true            # Other
  HotStandby: true       # Hot Standby

# Search Options
search_options:
  search_in: "Full Document"  # radio button: ContentPlaceHolderMainPageContent_RadioButtonFullDocument
  power_level:
    min: "0"      # dropdown: ContentPlaceHolderMainPageContent_DropDownListPowerLevelLow
    max: "100+"   # dropdown: ContentPlaceHolderMainPageContent_DropDownListPowerLevelHigh

# Form IDs and Names (for reference)
form_references:
  main_form: "aspnetForm"
  search_button: "ContentPlaceHolderMainPageContent_ButtonSearch"
  reset_button: "ContentPlaceHolderMainPageContent_ButtonReset"
  
  # Date Range Fields
  event_date_type: "ContentPlaceHolderMainPageContent_DropDownListDateType"
  report_date_type: "ContentPlaceHolderMainPageContent_DropDownListReportDateType"
  
  # Additional Search Options
  keywords_field: "ContentPlaceHolderMainPageContent_TextBoxKeywords"
  sort_by: "ContentPlaceHolderMainPageContent_DropDownListSortBy1"
  sort_order: "ContentPlaceHolderMainPageContent_DropDownListSortOrder1"

# Frame Information
iframe:
  id: "2sVFmGPGm"
  wait_time: 20  # seconds to wait for iframe to load